FROM python:3.11-bookworm

WORKDIR /app

# Устанавливаем curl и rustup (официальный способ установки Rust)
RUN apt-get update && apt-get install -y curl build-essential && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y && \
    export PATH="/root/.cargo/bin:$PATH" && \
    rustc --version && \
    pip install --upgrade pip

ENV PATH="/root/.cargo/bin:$PATH"

COPY service_sim/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY service_sim/ .
CMD ["python", "main.py"]
